
baseurl                = "http://bep.is"
languageCode           = "en-us"
title                  = "bep.is"
pygmentsStyle          = "trac"
disableKinds           = ["RSS", "sitemap", "taxonomy", "term"]
defaultContentLanguage = "en"
timeZone               = "Europe/Oslo"

defaultContentLanguageInSubdir = true

[deployment]
    [[deployment.targets]]
        name                     = "s3"
        url                      = "s3://bep.is?region=eu-west-1&prefix=root"
        cloudFrontDistributionID = "E1TX7TXFKWFR6S"
    [[deployment.matchers]]
        # Cache static assets for 1 year.
        pattern      = "^.+\\.(js|css|svg|ttf)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip         = true

    [[deployment.matchers]]
        pattern      = "^.+\\.(png|jpg)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip         = false

    [[deployment.matchers]]
        # Set custom content type for /sitemap.xml
        pattern     = "^sitemap\\.xml$"
        contentType = "application/xml"
        gzip        = true

    [[deployment.matchers]]
        pattern = "^.+\\.(html|xml|json)$"
        gzip    = true

[services]
    [services.googleAnalytics]
        id = "G-WSTN6R3X91"

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"

[module]
    [[module.imports]]
        path = "github.com/bep/hugo-mod-misc/render-hooks"

[params]
    description = "bep.is is a page about Bjørn Erik Pedersen."

[Languages]
    [Languages.en]
        weight       = 1
        languageName = "English"

    [Languages.nn]
        weight       = 2
        languageName = "norsk"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        respectDoNotTrack = true
        anonymizeIP       = true
        useSessionStorage = true
    [privacy.instagram]
        disable = true
    [privacy.speakerDeck]
        disable = true
    [privacy.twitter]
        enableDNT = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        privacyEnhanced = true
